version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: jakarta-backend
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: ecommerce_db
      DB_USER: root
      DB_PASSWORD: root

  frontend:
    build: ./frontend
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql-data:
